### ISSUE TITLE
E-mail notifications for users

### ISSUE THREAD

**Issue by astro** [nek0/yammat#1]
Wenn in meinem Namen etwas gekauft wird, hätte ich gern eine Mail.

Also:
- [x] Im User model eine E-Mail-Adresse erlauben
- [x] Evtl. im User model Notification gewünscht/unerwünscht
- [x] Bei User Registration Daten entgegennehmen
- [x] Bei Kauf/Guthaben Mail versenden
- [ ] Smarthost fürs E-Mail-Setup?

**Comment by nek0** [comment]
Zu deinen Punkten:

* Willst du tatsächlich jedes mal, wenn du etwas kaufst eine Mail bekommen?
* Mails werden schon vom System versendet, dazu braucht das System nur sendmail.

**Comment by nek0** [comment]
im neuesten commit eingepflegt.
