### ISSUE TITLE
JSON/XML config file für Inventar

### ISSUE THREAD

**Issue by vv01f** [nek0/yammat#10]
Die Liste von Produkten mit Eigenschaften sollte ggf. über ein config-file einrichtbar sein anstatt alles einzeln über die webformulare einzutippen.
Eine Backup-Funktion könnte re-deployment stark beschleunigen

**Comment by yater** [comment]
Wenn ich das Muster bekomme, so kann ich gern die [Inhalte](https://wiki.c3d2.de/Mate#Getr.C3.A4nke_im_Vergleich) liefern!

**Comment by nek0** [comment]
Backup ist auf jeden Fall machbar. Das rollback sehe ich als etwas schwieriger, aber ich sehe, was da geht.

**Comment by nek0** [comment]
Json backup und rollback eingeführt in fec1d19.
