### ISSUE TITLE
LTR/RTL overrides in user name break rendering of mails

### ISSUE THREAD

**Issue by majewsky** [nek0/yammat#106]
I recently prepended a U+202E character (*right-to-left override*) to my username. The web UI copes with that reasonably well:

----

![image](https://user-images.githubusercontent.com/24696/26895880-4d65e02e-4bc3-11e7-9a87-0e634287d8d5.png)

----

However, the U+202E "confuses" my mail application when I receive a purchase receipt:

![screenshot_20170607-204057](https://user-images.githubusercontent.com/24696/26895969-9c990cf2-4bc3-11e7-89e5-d2a21004fac1.png)

The [relevant section of the Unicode standard](http://www.unicode.org/reports/tr9/#Directional_Formatting_Codes) suggests that appending U+202D (left-to-right override) to the username should fix the display of the text that follows the username. I looked at the code and saw that `userIdent` is used in the templates, but I couldn't find where that function is defined.

**Comment by majewsky** [comment]
The behavior seems to be client-dependent, though. KMail on desktop correctly resets directionality at the end of the line:

![image](https://user-images.githubusercontent.com/24696/26897791-ff7a7742-4bc9-11e7-90ce-1e96ec43ca97.png)

So there is also a bug with K-9 Mail (the app that generated the notification above) here. It joins lines together for the notification, which results in the incorrect rendering. However, even in the KMail screenshot above, the comma is still misplaced, so the U+202D suffix is still appropriate.

**Comment by nek0** [comment]
And what can I possibly do about it?

**Comment by majewsky** [comment]
See second-to-last sentence in the first comment:

> ...appending U+202D (left-to-right override) to the username should fix the display of the text that follows the username.

**Comment by vv01f** [comment]
I think this should be done on framework level rather than on the application itself

* check for special case on string-level (not only on username as the same might be the case for other strings)
* conditionally append the proposed opposite bytemark for reverting to yammat standard writing direction

**Comment by nek0** [comment]
So there's nothing I can do about it.
