### ISSUE TITLE
Tausender-Trennzeichen erwünscht

### ISSUE THREAD

**Issue by vv01f** [nek0/yammat#11]
alle 10^3 wäre ein Punkt sehr hübsch sagte ein WiWi gerade..

**Comment by yater** [comment]
Ein Hoch der [Norm (ISO 80000)](https://de.wikipedia.org/wiki/Internationales_Gr%C3%B6%C3%9Fensystem#ISO_80000_und_IEC_80000), die wirtschaftswissenschaftliche Gepflogenheit sind.

**Comment by eri451** [comment]
Welcher Schreibweise folgt die Norm? 1,000.00 oder 1.000,00?

**Comment by yater** [comment]
:-D Ein Hoch der Regionalität! :-D
Ist mir, bezüglich des Projektes, eher egal. Es sollte halt nur einheitlich sein. 
Ich bin ja eher mit '1.000,00' sozialisiert wurden, aber das muss ja nichts heißen. Sonst wird ja aber bisher '0.00' ausgewiesen.

**Comment by nek0** [comment]
Ich sehe, was ich tun kann. Mal sehen, ob ich die floats umformattiert bekomme.

**Comment by nek0** [comment]
Tausender-Trennzeichen nach deutscher Tradition eingefügt in acdf3e8.
