### ISSUE TITLE
Kassensturz

### ISSUE THREAD

**Issue by yater** [nek0/yammat#12]
Gelegentlich kommt es zu einer Zählung der Kasse. Der dort ermittelte Betrag sollte (wert)berichtigend eingetragen werden können und (unverzüglich) Wirksamkeit erlangen.
> Gegenstand der aktuellen Implementierung, meinem Verständnis nach, ist der Ersatz für das Wesen der [Mate-Kasse](https://wiki.c3d2.de/Mate-Kasse). Dabei ist eben üblich neben dem Soll-Bestand gelegentlich auch der Ist-Bestand ermittelt wird. Ein Hoch der Inventur!

**Comment by nek0** [comment]
Das ist so nicht vorgesehen, da es doch ein ziemliches Missbrauchpotential hat. man darf nicht vergessen, dass jeder ohne authentifizierung alle Aktionen am Matematen durchführen kann. Ich wäre dafür, dass solche Wertberichtigungen direlt mit der Datenbank abgeklärt werden.

**Comment by astro** [comment]
Direkter Datenbankzugriff mag nicht für jeden Kassenstürzer der beste Weg sein. Wie wärs mit einem Vermerk im Journal?

**Comment by nek0** [comment]
Kassnesturz könnte den Eintrag unter "cashier" aktualisieren, aber ich würde das nicht als Transaktion sehen.

**Comment by nek0** [comment]
Kassenstürze eingeführt in d4609d1.
