### ISSUE TITLE
User E-Mail Changes müssen vom bisherigen E-Mail-Empfänger bestätigt werden

### ISSUE THREAD

**Issue by astro** [nek0/yammat#13]
Security feature.

1. Pick victim user.
2. Turn E-Mail notifications off.
3. Pick victim user again.
4. Do purchases in their name. Victim won't notice.
5. Pick victim user once more.
6. Turn E-Mail notifications off.
7. Profit!

**Comment by vv01f** [comment]
vorschlag: notify über profiländerungen

**Comment by nek0** [comment]
war ne Scheißidee, das mit den notifications...

**Comment by vv01f** [comment]
ne, die is nur ausbaufähig.. einfach noch eine wenn notify angestellt wird
oder deaktivieren geht nur mit hilfe des kätzchens :D

**Comment by nek0** [comment]
wird zwar etwas meta, das mit den notifications über notifications, aber ich lasse mir was einfallen.

**Comment by vv01f** [comment]
mh.. zum abschalten nen token-link der an die email kommt zum abstellen oder alternativ den mauzemann anflehen.. wieder n problem mit dem speichern :\

**Comment by nek0** [comment]
Ist nun in 848f00c gelöst wie folgt:
An die vorherig eingetragene Mailadresse geht eine Mail raus, welche über die Änderung informiert.
