### ISSUE TITLE
andere zuspammen mit fake-accounts

### ISSUE THREAD

**Issue by vv01f** [nek0/yammat#14]
email eines anderen eintragen und lustig aktionen aufsführen
fix wahrscheinlich ähnlich issue #13

**Comment by nek0** [comment]
Wir dürfen hier nicht vergessen, dass das gesamte System immer noch vertrauensbasiert ist. Momentan versucht man hier viel zu sehr Sicherheitsfeatures durchzudrücken, für welche das System anfangs nicht vorgesehen war.

**Comment by vv01f** [comment]
hasse reschd
