### ISSUE TITLE
User-/Waren-Avatar

### ISSUE THREAD

**Issue by astro** [nek0/yammat#2]
Nicht wichtig, aber würde die Benutzung verschönern. Z.B. durch:
* Bild-Upload
* Bild-URL
* Gravatar mit E-Mail-Adresse aus #1

**Comment by nek0** [comment]
Habe mich eingehend mit Avataren beschäftigt. leider erfolglos. Wird in der Priorität ganz nach hinten geschoben.

**Comment by nek0** [comment]
eingeführt.
