### ISSUE TITLE
"etwas für 50 cemt"

### ISSUE THREAD

**Issue by vv01f** [nek0/yammat#25]
..ist en Produkt im Inventar weil man eventuell mal ein Stück Pizza bezahlen möchte oder ein Brötchen, ein belegtes Brot etc.
leider macht das aus zwei Gründen weniger Sinn im Inventar
1. es wird nicht sauber übersetzt und ist kein toller Produktname
2. es hat keinen begrenzten Bestand

Kann man eine $Einheit als Pseudo-Item aufnehmen? :)

**Comment by nek0** [comment]
Ich könnte höchstens einen Button einführen, mit dem man teile seines Guthabens spenden kann. Finde ich aber nicht so schön. Wenn jemand ein Produkt anbietet wie belegte Brote, so soll er sie auch schön eintragen.

**Comment by vv01f** [comment]
nagut, ist nachvollziehbar nicht gewollt
