### ISSUE TITLE
Alte Nutzer reaktivieren/nur deaktivierte anzeigen

### ISSUE THREAD

**Issue by s72785** [nek0/yammat#3]
Bei der Auswahl der zu reaktivierenden Nutzer werden nicht nur die angezeigt, die reaktiviert werden können, sondern auch bereits aktive. Diese sollten ggf. nicht angezeigt werden [oder abgegrenzt per css ausgeblendet sein falls das als "Verlängerung" benutzbar sein soll (imho unnötig)].

**Comment by nek0** [comment]
fixed in 83210db
