### ISSUE TITLE
bug: inventory

### ISSUE THREAD

**Issue by vv01f** [nek0/yammat#45]
wiederherstellen des frisch exportierten files funzt bei vater nicht, bei mir schon.

änderungen am json werden bei mir aber nicht übernommen, die erfolgsmeldung bleibt dennoch.

vermutung: avatar fehlt im export?! und rückgabewert ist nicht korrekt ausgewertet...

**Comment by nek0** [comment]
beim exportieren ins json werden alle Avatare verworfen. Das ist feature, ansonsten würden die jsons zu groß werden.

**Comment by s72785** [comment]
es geht darum, dass wir den bestand so nicht bulk-aktualisieren können.
wiederherstellen funzt nicht wie erwünscht.

**Comment by nek0** [comment]
fixed.
