### ISSUE TITLE
Durchflussmenge (Sensor) ohne das Vorhalten von mehreren einzelnen Transaktionen

### ISSUE THREAD

**Issue by yater** [nek0/yammat#58]
Mir ging die Idee zur Bereitstellung einer Größe der momentanen Durchflussmenge (als eine Art Sensor) nicht aus dem Kopf. Bedenklich erschien ja, dass dazu die Transaktionen zum Ausfassen (aka buy) gespeichert werden müssen. (Wer hat was wann gekauft?) Dann wird daraus errechnet wie hoch die Durchflussmenge ist, oder? Demnach bräuchte es das Vorhalten aller Transaktionen der letzten Stunde (bei der Bestimmung der Durchflussmenge je Stunde).
Was wäre aber wenn nicht es nur zu einer Speicherung der Transaktionen kommen müsste, sondern die Durchflussmenge (mit ergänzenden zeitabhängigen Daten) alleinstehend wäre und die Grundlage für einen nachfolgenden Wert wäre.
Aus meiner "spontanen" Überlegung heraus müsste das wie folgt möglich sein:
Die Durchflussmenge ist ein Wert in l (oder ml), der ergänzend immer mit einem Zeitpunkt versehen ist. Des weiteren gibt es eine Konstante, die eine Zeit (z. B. 10 Minuten) darstellt, bei der spätestens ein Aktion ausgeführt wird.
Exemplarisch werden in der Minute 0 6 Flaschen zu 0,5 l gekauft.
Fall 0: Die Durchflussmenge ist 0. Die Durchflussmenge wird mit 3 l bestimmt.
Fall 1: Es passiert nichts (vor dem Ablauf der Konstanten), lediglich die Zeit verstreicht für die Dauer der Konstanten. Die Durchflussmenge ist nicht 0, sondern 3 l. Demnach wird beim ersten Ablauf der Wert auf 2,5 gemindert, da seit 10 min : 60 min nichts passiert ist und demnach der Wert um diesen Quotienten verringert werden würde. Nach dem zweiten Ablauf würde der Wert auf 2 gemindert, da seit 20 min : 60 min nichts passiert ist. (Im Übrigen würde nach 60 min der Wert der Durchflussmenge auf 0 gesetzt werden und der Zeitpunkt könnte gelöscht werden.)
Fall 2: Nach 25 min werden 2 Flaschen zu 0,5 l gekauft. Erst einmal wird die exakte (bisherige) Durchflussmenge bestimmt und die neue Menge addiert. (25 min : 60 min) · 3 l + 2 · 0,5 l = 2,75 l. Es wird ein neuer Zeitpunkt gesetzt, um den potentiellen Ablauf der nächsten Konstante zu bestimmen.
Passt das (oder habe ich gerade einen verqueren Ansatz im Kopf)?
Die Größe der Anzahl von Einheiten (Flaschen) habe ich erst einmal herausgelassen, obwohl sie relevant sein könnte.
(Ich könnte (vor Ärger) im Boden versinken, dass ich das nicht nek0-like einfach mal implementieren kann.)

**Comment by s72785** [comment]
ich verstehe das so... es handelt sich um einen yammat-sensor, der artikel-eigenschaften auf den verbrauch abbilden kann.. an diesem beispiel eben das Volumen der konsumierten Flüssigkeiten

input: 
betrachtung_zeitraum = 60*60 = 3600 // 60min => Zeiteinheit von time()
anzahl des gerade gebuchten artikels // bei reiner anzeige 0
volumen des artikels

menge_neu = anzahl * volumen
if ( menge_neu > 0 ) {
zeit_anfang = speicher({menge, zeitpunkt}[zeitpunkt])
zeit_ende = time() // ich nehme an, die Einheit ist hier in Sekunden
delta = zeit_ende - zeit_anfang
speicher[menge] = d * speicher[menge] + 
speicher[zeitpunkt] = time()
}
output: "aktuelle duchflussmenge ist:" speicher[menge]

ergo, wir benötigen noch die eigenschaft "getränke"volumen für die getränke (nicht-getränke = 0, oder falls wasseranteil dieser)
eventuell wären gleichlautend weitere eigenschaften noch genauso interessant wie kalorien -> kalorienverbrauch -> weiterer sensor, gleiche berechnung

**Comment by nek0** [comment]
"Durchflusssensor" ist extern implementiert. wird geschlossen.
