### ISSUE TITLE
Benachrichtigung  per mail zu Koffeinkonsum-Limit

### ISSUE THREAD

**Issue by vv01f** [nek0/yammat#7]
basierend auf der Konsummenge sollte manch ein Teilnehmer gesundheitlich beraten werden
ggf auch "Runden um das GCHQ" empfehlen bei Kalorien usw.

**Comment by astro** [comment]
Solch Verfolgung lässt das Datenmodell nicht zu. Und das ist auch gut so. Close?

**Comment by vv01f** [comment]
mh, wegen Privacy oder weil man nicht einfach das Datenmodell erweitern kann?
tracking braucht ja nur optional sein wie auch Benachrichtigung schon, vater hat interesse und ich halte mich jetzt auch gerade fürverdächtig wach :}

**Comment by nek0** [comment]
Das momentane Modell sieht sowas nicht vor. Es wäre implementierbar, aber da das System sehr offen gestaltet ist, könnte dann jeder diese "Gesundheitsdaten" einsehen. Ich glaube da haben einige entschieden was dagegen.
