### ISSUE TITLE
Add new item: Barcode field missing

### ISSUE THREAD

**Issue by toothstone** [nek0/yammat#70]
The barcode field is only available if you're editing an existing item.

**Comment by astro** [comment]
How are you going to edit a non-existent item?

**Comment by toothstone** [comment]
Maybe I should have given a little more detail:
In the Inventory ⇒ Edit Item dialog there is a field for adding/editing barcodes.
In the Restock Inventory ⇒ Add New Item dialog this field is missing, which seems inconsistent to me.

**Comment by s72785** [comment]
@Astro:
current workflow
- add new item, enter some details
- edit item again to add barcode
=> somehow complicated, so he is right

**Comment by nek0** [comment]
fixed in a39db41.
