### ISSUE TITLE
new attribute for product: responsiblePerson

### ISSUE THREAD

**Issue by vv01f** [nek0/yammat#79]
- prevent spamming a single person
- have better information on current product level for buyers

messages on low volume are right now sent to one single email, this should be changed to send them conditionally on the product; supposedly the main consumer or usual buyer

**Comment by nek0** [comment]
The spam factor has been drastically reduced. Only one email is sent when the current stock falls under the threshold.

Additionally, there is the possibility to configure multiple recipients for the alert messages.
