### ISSUE TITLE
last-active bei kauf, nicht nur bei aufladen

### ISSUE THREAD

**Issue by s72785** [nek0/yammat#82]
um den Zeitpunkt der letzten Aktivität nicht zu genau zu speichern genügt tages-/monats-/wochengenau zu erfassen statt einen kompletten Zeitstempel mit Sekunden

also statt 16-01-12T16:21:23
einfach 16-01 für monats-genau
oder 16-2 für wochengenau
oder 16-12 für (julianisch) tagesgenau
oder so ähnlich ...

**Comment by nek0** [comment]
Seit 0.0.3: Timestamps sind nun nur tagesgenau und werden auch beim Kauf aktualisiert.
