### ISSUE TITLE
Kaufen auch bei Leerstand erlauben

### ISSUE THREAD

**Issue by astro** [nek0/yammat#9]
Manchmal ist es wichtiger schnell etwas zu bezahlen statt mal eben eine Inventur durchzuführen.

**Comment by yater** [comment]
Zustimmung! Eher stellt sich meiner Ansicht nach die Frage, ob ein negativer Bestand zulässig sein soll.

**Comment by eri451** [comment]
Wie darf man sich einen negativen Bestand vorstellen?

**Comment by yater** [comment]
… wie einen "schlichtweg" falschen Bestand? Also ein negative Abweichung zwischen Soll- und Ist-Bestand kann es ja auch bei einem noch positiven Bestand geben. 
Abweichend davon wäre hier natürlich offensichtlicher, dass es zu einer Wertberichtigung kommen muss.
Spontan hänge ich natürlich gar nicht an einem negativen Bestand, wohl eher im Gegenteil. Schließlich hätte das Verharren bei 0 dann eher den Charakter einer an der Realität orientierten Bereinigung des Missstände und würden auf die Berichtigung hinwirken.

**Comment by nek0** [comment]
Über die Übersicht und das Bearbeiten der Produkte kann ja jederzeit der bestand korrigiert werden. Ich sehe nicht, dass ich da was machen sollte.
