### ISSUE TITLE
add property 'buying price'

### ISSUE THREAD

**Issue by vv01f** [nek0/yammat#91]
to ensure pricetags are not lower than this mark

deals with the issue that peolpe lower prices in inventory and betray the system

idealy the buying price can be changed with a given reason and this is logged as well

**Comment by nek0** [comment]
Buying price could be derived from the price per crate already stored in the beverage data. That would not be the Problem. Problem is, that this is again one of these security issues for which this system was not designed. This system is trust based. If that does not suffice, feel free to implement a system with authentication and authorization.

I don't say I won't do it, but I see a conflict with one of the core ideas.

**Comment by nek0** [comment]
since there have been no further comments on this I close this now.
